Repository dwavesystems/dimod, pull requests merged in 2018-05, with the labels that each got.

#185 Disable pip update in appveyor build
  appveyor.yml
  appveyor/install.ps1
  appveyor/run_with_env.cmd
Labels: bug

#183 Add BinaryQuadraticModel.to_coo and BinaryQuadraticModel.from_coo
  dimod/binary_quadratic_model.py
  dimod/io/coo.py
  docs/reference/binary_quadratic_model.rst
  tests/data/coo_qubo.qubo
  tests/test_binary_quadratic_model.py
  tests/test_io_coo.py
Labels: enhancement

#190 Restructure intro, update BQM and its methods (add, remove, update)
  README.rst
  dimod/binary_quadratic_model.py
  dimod/core/sampler.py
  dimod/core/structured.py
  docs/conf.py
  docs/index.rst
  docs/introduction.rst
  docs/reference/binary_quadratic_model.rst
  docs/reference/index.rst
  docs/test.py
  docs/test.txt
  docs/tmp.qubo
  tmp.ising
  tmp.qubo
  tmp.txt
  tmp2.qubo
Labels: documentation

#195 Add all chain variable to target bqm with embed_bqm
  dimod/embedding/transforms.py
  tests/test_embedding.py
Labels: bug
