Repository dwavesystems/dimod, pull requests merged in 2019-10, with the labels that each got.

#535 Fix make_quadratic bug
  dimod/higherorder/utils.py
  tests/test_higherorder.py
Labels: bug/fix

#536 Add offset and vartype properties to cybqm
  dimod/bqm/adjarraybqm.pxd
  dimod/bqm/adjarraybqm.pyx
  dimod/bqm/adjdictbqm.py
  dimod/bqm/adjmapbqm.pxd
  dimod/bqm/adjmapbqm.pyx
  dimod/bqm/adjvectorbqm.pxd
  dimod/bqm/adjvectorbqm.pyx
  dimod/vartypes.py
  tests/test_bqm.py
Labels: feature-request/enhancement

#537 Fix serialization of samplesets with non-integer sample values
  dimod/sampleset.py
  tests/test_sampleset.py
Labels: bug/fix

#540 Generator functions now accept edgelists as graphs
  dimod/decorators.py
  dimod/generators/chimera.py
  dimod/generators/fcl.py
  dimod/generators/random.py
  tests/test_decorators.py
  tests/test_generators.py
Labels: feature-request/enhancement

#544 Return numpy scalars from cybqm objects
  dimod/bqm/adjarraybqm.pxd
  dimod/bqm/adjarraybqm.pyx
  dimod/bqm/adjdictbqm.py
  dimod/bqm/adjmapbqm.pxd
  dimod/bqm/adjmapbqm.pyx
  dimod/bqm/adjvectorbqm.pxd
  dimod/bqm/adjvectorbqm.pyx
  dimod/bqm/utils.pxd
  dimod/bqm/utils.pyx
  setup.py
  tests/test_bqm.py
Labels: feature-request/enhancement

#539 Add ConnectedComponentComposite
  dimod/__init__.py
  dimod/reference/composites/__init__.py
  dimod/reference/composites/connectedcomponent.py
  dimod/traversal.py
  docs/reference/bqm/bqm_functions.rst
  docs/reference/sampler_composites/composites.rst
  tests/test_connectedcomponentscomposite.py
  tests/test_traversal.py
Labels: feature-request/enhancement

#549 Only make cybqms available in python 3.5+
  dimod/bqm/__init__.py
  dimod/bqm/src/adjarray.cc
  dimod/bqm/src/adjarray.h
  dimod/bqm/src/adjmap.cc
  dimod/bqm/src/adjmap.h
  dimod/bqm/src/adjvector.cc
  dimod/bqm/src/adjvector.h
  setup.py
  tests/test_adjarraybqm.py
  tests/test_adjmapbqm.py
  tests/test_adjvectorbqm.py
Labels: WIP: Do not merge, feature-request/enhancement

#551 Support vartype str/set inputs in make_quadratic
  dimod/higherorder/utils.py
  tests/test_higherorder.py
Labels: feature-request/enhancement

#555 Change FixedVariableComposite to handle non-blocking child samplers
  dimod/reference/composites/fixedvariable.py
Labels: feature-request/enhancement
