Repository dwavesystems/dimod, pull requests merged in 2019-02, with the labels that each got.

#399 Add SampleSet.truncate method
  dimod/sampleset.py
  docs/reference/sampleset.rst
  tests/test_sampleset.py
Labels: feature-request/enhancement

#384 Bson serialization bug fixes2
  dimod/binary_quadratic_model.py
  dimod/serialization/bson.py
  tests/test_binary_quadratic_model.py
  tests/test_serialization_bson.py
Labels: WIP: Do not merge, bug/fix

#405 Support pickling BQMs
  dimod/views.py
  tests/test_binary_quadratic_model.py
Labels: bug/fix

#406 Require numpy 1.15 and support 1.16
  dimod/higherorder.py
  dimod/reference/composites/spin_transform.py
  setup.py
Labels: bug/fix

#409 Do not keep unset linear biases in memory
  dimod/binary_quadratic_model.py
  dimod/views.py
  tests/test_binary_quadratic_model.py
Labels: feature-request/enhancement

#415 SampleSet.data_vectors
  dimod/sampleset.py
  tests/test_sampleset.py
Labels: feature-request/enhancement

#417 Fix SpinReversalTransform to correctly apply spin reversals
  dimod/reference/composites/spin_transform.py
Labels: bug/fix

#420 Refactor serialization
  MANIFEST.in
  dimod/binary_quadratic_model.py
  dimod/sampleset.py
  dimod/serialization/bqm_json_schema.json
  dimod/serialization/bson.py
  dimod/serialization/json.py
  dimod/serialization/sampleset_json_schema.json
  dimod/serialization/utils.py
  docs/reference/utilities.rst
  tests/test_binary_quadratic_model.py
  tests/test_sampleset.py
  tests/test_serialization_bson.py
  tests/test_serialization_json.py
  tests/test_serialization_utils.py
Labels: feature-request/enhancement
