Repository dwavesystems/dimod, pull requests merged in 2019-01, with the labels that each got.

#353 Benchmarking
  .gitignore
  benchmarks/asv.conf.json
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/bench_binary_quadratic_model.py
  benchmarks/requirements.txt
Labels: enhancement

#354 Speed up BQM.add_variable and BQM.add_interaction
  dimod/binary_quadratic_model.py
Labels: enhancement

#355 Return dict for BQM.to_ising/.to_qubo
  dimod/binary_quadratic_model.py
Labels: bug

#360 Fix as_samples empty case
  benchmarks/benchmarks/__init__.py
  benchmarks/benchmarks/bench_as_samples.py
  benchmarks/benchmarks/bench_binary_quadratic_model.py
  benchmarks/benchmarks/common.py
  benchmarks/requirements.txt
  dimod/__init__.py
  dimod/sampleset.py
  docs/reference/sampleset.rst
  tests/test_sampleset.py
Labels: bug/fix

#330 Add HigherOrderComposite
  dimod/__init__.py
  dimod/higherorder.py
  dimod/reference/composites/__init__.py
  dimod/reference/composites/higherordercomposite.py
  docs/reference/bqm_functions.rst
  docs/reference/ref_samplers_composites.rst
  tests/test_higherorder.py
  tests/test_higherordercomposite.py
Labels: feature-request/enhancement

#368 Add reverse parameter to SampleSet.data
  dimod/sampleset.py
  tests/test_sampleset.py
Labels: feature-request/enhancement

#370 SampleSet.__str__
  dimod/__init__.py
  dimod/sampleset.py
  dimod/serialization/format.py
  tests/test_serialization_format.py
Labels: feature-request/enhancement

#377 Don't change vartype of bqm unnecessarily
  dimod/core/sampler.py
  tests/test_sampler.py
Labels: feature-request/enhancement

#385 Add assert_bqm_almost_equal
  dimod/testing/asserts.py
  docs/reference/testing.rst
  tests/test_testing.py
Labels: feature-request/enhancement

#387 minor scaling updates
  dimod/binary_quadratic_model.py
  dimod/reference/composites/scalecomposite.py
  tests/test_binary_quadratic_model.py
  tests/test_scalecomposite.py
Labels: feature-request/enhancement

#383 Feature/sampleset to df compress
  dimod/sampleset.py
  tests/test_sampleset.py
Labels: feature-request/enhancement
