Repository dwavesystems/dimod, pull requests merged in 2021-08, with the labels that each got.

#939 Add numpy
  dimod/generators/constraints.py
Labels: feature-request/enhancement

#936 Add `CQM.from_bqm`, `CQM.from_dqm` and `CQM.from_qm`
  dimod/constrained.py
  dimod/discrete/discrete_quadratic_model.py
  docs/reference/constrained.rst
  docs/reference/dqm.rst
  releasenotes/notes/DQM.get_cases-5a0d84176c5b07ac.yaml
  releasenotes/notes/cqm-from-bqm-dqm-qm-707a871f0f3ac79a.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement

#940 Some small improvements to QM docs
  dimod/quadratic/quadratic_model.py
  dimod/views/quadratic.py
  docs/reference/bqm.rst
  docs/reference/index.rst
  docs/reference/quadratic.rst
Labels: feature-request/enhancement

#938 Unique variable label feature
  dimod/binary/binary_quadratic_model.py
  dimod/decorators.py
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/unique_variable_label_feature-5e890d6ebd7759a9.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#942 Add Spins, Binaries and Integers functions
  dimod/binary/binary_quadratic_model.py
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/Binaries-and-Spins-and-Integers-bfed01e0c2b5f6cd.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#944 Fix adding integer variables with bounds via `CQM.add_constraint_from_iterable`
  dimod/constrained.py
  releasenotes/notes/fix-integer-bounds-in-constraint-by-terms-70f2f19c85ecc2e6.yaml
  tests/test_constrained.py
Labels: bug/fix

#946 Add quicksum function
  dimod/binary/binary_quadratic_model.py
  dimod/quadratic/quadratic_model.py
  docs/reference/quadratic.rst
  releasenotes/notes/add-quicksum-373672fff48775a4.yaml
  tests/test_symbolic.py
Labels: feature-request/enhancement

#948 Add `CQM.substitute_self_loops` method
  dimod/binary/binary_quadratic_model.py
  dimod/constrained.py
  dimod/decorators.py
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  dimod/utilities.py
  docs/reference/constrained.rst
  docs/reference/quadratic.rst
  releasenotes/notes/add-QM.remove_interaction-e97a7ac91db2e2b8.yaml
  releasenotes/notes/feature-CQM.substitute_self_loops-eb5a4952ee2a460a.yaml
  tests/test_bqm.py
  tests/test_constrained.py
  tests/test_quadratic_model.py
Labels: bug/fix, feature-request/enhancement

#956 corrected variable types in cqm docstring
  dimod/constrained.py
Labels: bug/fix

#955 Support a superset of variables in BQM/QM.energies
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/permissive-energies-ce39fea1c68d074b.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#952 Add CQM methods examples
  dimod/constrained.py
Labels: feature-request/enhancement

#957 Add logic gates to generators
  dimod/generators/__init__.py
  dimod/generators/gates.py
  docs/reference/quadratic.rst
  releasenotes/notes/gate-generators-43208669a09df0d8.yaml
  tests/test_generators.py
Labels: feature-request/enhancement

#961 Add linear slack method
  dimod/discrete/discrete_quadratic_model.py
  releasenotes/notes/add-linear-slack-dqm-25312a5fe23574e6.yaml
  tests/test_discrete_quadratic_model.py
Labels: feature-request/enhancement

#964 Add binery_encoding generator
  dimod/generators/__init__.py
  dimod/generators/integer.py
  docs/reference/quadratic.rst
  releasenotes/notes/binary-encoding-generator-82b1cfb9fd0e571a.yaml
  tests/test_generators.py
Labels: feature-request/enhancement

#967 Account for offset when multiplying models symbolically
  dimod/binary/binary_quadratic_model.py
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/fix-symbolic-offset-multiplication-803d2e8f1708a8fb.yaml
  tests/test_bqm.py
  tests/test_symbolic.py
Labels: bug/fix

#968 Refactor variable tracking in ConstrainedQuadraticModel
  dimod/constrained.py
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/cqm-source-of-truth-96715b88d1cef87c.yaml
  tests/test_constrained.py
  tests/test_serialization_fileview.py
Labels: feature-request/enhancement, backwards compatibility break

#972 Add `cqm_to_bqm` function
  dimod/constrained.py
  docs/reference/constrained.rst
  releasenotes/notes/cqm-to-bqm-d369043cc341c5a3.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement

#978 Add CQMToBQMInverter.to_dict() and .from_dict()
  dimod/constrained.py
  releasenotes/notes/inverter-json-44f8d5caa74cf335.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement
