Repository dwavesystems/dimod, pull requests merged in 2021-07, with the labels that each got.

#865 Add `QuadraticModel`
  .gitignore
  dimod/__init__.py
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/include/dimod/iterators.h
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/__init__.pxd
  dimod/quadratic/__init__.py
  dimod/quadratic/cyqm/__init__.pxd
  dimod/quadratic/cyqm/__init__.py
  dimod/quadratic/cyqm/cyqm_base.pxd
  dimod/quadratic/cyqm/cyqm_base.pyx
  dimod/quadratic/cyqm/cyqm_float32.pxd
  dimod/quadratic/cyqm/cyqm_float32.pyx
  dimod/quadratic/cyqm/cyqm_float64.pxd
  dimod/quadratic/cyqm/cyqm_float64.pyx
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/QuadraticModel-0618bcac78cb1136.yaml
  setup.cfg
  setup.py
  tests/test_bqm.py
  tests/test_quadratic_model.py
  tests/test_symbolic.py
  testscpp/tests/test_quadratic_model.cpp
Labels: feature-request/enhancement

#876 Use delvewheel.
  .circleci/config.yml
Labels: feature-request/enhancement

#877 Add QM serialization
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  dimod/serialization/fileview.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#879 Add `ConstrainedQuadraticModel.add_discrete`
  dimod/constrained.py
  releasenotes/notes/CQM.add_discrete-585f85df96ebea36.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement

#880 Add `QM.spin_to_binary`, `QM.energies` and `QM.energy`
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#885 Support legacy BQM types in CQM
  dimod/constrained.py
  releasenotes/notes/AdjVector-and-AdjDict-in-CQM-f1f6c27c02fa799c.yaml
  tests/test_constrained.py
Labels: bug/fix

#886 Improve performance of copy operations
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary/vartypeview.py
  dimod/cyvariables.pxd
  dimod/cyvariables.pyx
  releasenotes/notes/BQM.is_almost_equal-3f46008eeffbe290.yaml
  releasenotes/notes/Variables.copy-3d7b76801cce1644.yaml
  releasenotes/notes/fix-pyBQM-copy-3433abf9f39f8137.yaml
  tests/test_bqm.py
  tests/test_variables.py
Labels: bug/fix, feature-request/enhancement

#888 Support specifying lower and upper bounds for integer variables in quadratic models
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/integer-range-in-QM-55af1cb29d0d3268.yaml
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#889 Remove SampleSet.is_writeable functionality
  dimod/decorators.py
  dimod/sampleset.py
  dimod/utilities.py
  dimod/variables.py
  releasenotes/notes/deprecate-writeable-848e70cddeb43d67.yaml
  tests/test_sampleset.py
  tests/test_utilities.py
Labels: backwards compatibility break

#891 Deprecate AdjVectorBQM and AdjDictBQM
  dimod/bqm/adjdictbqm.py
  dimod/bqm/adjvectorbqm.pxd
  dimod/bqm/adjvectorbqm.pyx
  dimod/generators/random.py
  dimod/reference/composites/fixedvariable.py
  releasenotes/notes/deprecate-adjvector-adjdict-6363b61fc68a2725.yaml
Labels: backwards compatibility break

#894 Deprecate dwave-preprocessing composites
  .circleci/config.yml
  dimod/reference/composites/_preprocessing.py
  dimod/reference/composites/clipcomposite.py
  dimod/reference/composites/connectedcomponent.py
  dimod/reference/composites/fixedvariable.py
  dimod/reference/composites/roofduality.py
  dimod/reference/composites/scalecomposite.py
  dimod/reference/composites/spin_transform.py
  dimod/roof_duality/fix_variables.py
  docs/reference/sampler_composites/composites.rst
  releasenotes/notes/move-preprocessing-composites-32800c78827f40c9.yaml
  tests/test_clipcomposite.py
  tests/test_connectedcomponentscomposite.py
  tests/test_fixedvariablecomposite.py
  tests/test_roof_duality.py
  tests/test_scalecomposite.py
  tests/test_spin_transform.py
Labels: backwards compatibility break

#895 Fix some deprecation warnings
  dimod/bqm/adjvectorbqm.pyx
  tests/test_spin_transform.py
Labels: bug/fix

#896 Add preprocessing to extras_require
  .circleci/config.yml
  releasenotes/notes/preprocessing-extras-install-7f0cbed8a24c195e.yaml
  setup.py
Labels: feature-request/enhancement

#897 Use new BQM in load_sampler_bqm_tests
  dimod/testing/asserts.py
  dimod/testing/sampler.py
Labels: feature-request/enhancement

#900 Cythonize `QM.from_bqm`
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#907 Consistency Update
  dimod/__init__.pxd
  dimod/binary/__init__.pxd
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary/vartypeview.py
  dimod/constrained.py
  dimod/quadratic/__init__.pxd
  dimod/quadratic/cyqm/__init__.pxd
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  releasenotes/notes/BQM.data.vartype-method-ba96dce5716ffa4c.yaml
  releasenotes/notes/CQM.add_discrete-return-label-758b7756d0fc378b.yaml
  releasenotes/notes/cimport-cyBQM-and-cyQM-77968e09ebcd685d.yaml
  releasenotes/notes/cyBQM-and-cyQM.data-20ce921b78af8cdd.yaml
  tests/test_constrained.py
Labels: backwards compatibility break, bug/fix, feature-request/enhancement

#908 Fix pyBQM.add_linear and pyBQM.add_quadratic
  dimod/binary/pybqm.py
  releasenotes/notes/fix-pyBQM.add_linear-and-pyBQM.add_quadratic-0cad64ada2b9fdea.yaml
  tests/test_bqm.py
Labels: bug/fix

#910 Add `QuadraticModel.change_vartype`
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/QuadraticModel.change_vartype-cc4d44ea80622ee3.yaml
  releasenotes/notes/c++-QuadraticModel-vartype-manipulation-aec04b236f797258.yaml
  tests/test_quadratic_model.py
  testscpp/tests/test_quadratic_model.cpp
Labels: bug/fix, feature-request/enhancement

#909 Refresh circleci
  .circleci/config.yml
Labels: feature-request/enhancement

#916 Fix `QM.energies` to not cast samples to `int8`
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  releasenotes/notes/QM-integer-energy-b17f552ddd3b5f69.yaml
  tests/test_quadratic_model.py
Labels: bug/fix

#915 Inequality bugfix 2
  dimod/binary/binary_quadratic_model.py
  dimod/discrete/discrete_quadratic_model.py
  releasenotes/notes/fix_inequlity_energy-0adf721256a75a30.yaml
  tests/test_bqm.py
  tests/test_discrete_quadratic_model.py
Labels: bug/fix

#917 Fix/add empty bqm
  dimod/include/dimod/quadratic_model.h
  tests/test_bqm.py
Labels: bug/fix

#924 Make dwave-preprocessing a full dependency
  .circleci/config.yml
  dimod/reference/composites/_preprocessing.py
  dimod/reference/composites/clipcomposite.py
  dimod/reference/composites/connectedcomponent.py
  dimod/reference/composites/fixedvariable.py
  dimod/reference/composites/roofduality.py
  dimod/reference/composites/scalecomposite.py
  dimod/reference/composites/spin_transform.py
  releasenotes/notes/preprocessing-full-dependency-2a62f62e36d5ace6.yaml
  requirements.txt
  setup.py
Labels: bug/fix

#926 Fix `pyBQM.energies` with a single variable and integer bias.
  dimod/binary/pybqm.py
  releasenotes/notes/fix-pyBQM-energies-singleton-integer-2c30d3f64323f15b.yaml
  tests/test_bqm.py
Labels: bug/fix

#929 Fix integer bounds in QM and CQM
  dimod/constrained.py
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/QM.bounds-00653aa2d29f6b98.yaml
  releasenotes/notes/bounds-in-CQM-306a22e93ea069d3.yaml
  tests/test_constrained.py
  tests/test_quadratic_model.py
Labels: bug/fix, feature-request/enhancement

#930 Add a few module-level docs and other structure hints
  dimod/bqm/README.rst
  dimod/core/sampler.py
  dimod/libcpp.pxd
  dimod/meta.py
  dimod/typing.py
  releasenotes/notes/remove-dimod-meta-610179e374ab9058.yaml
Labels: feature-request/enhancement

#931 Make `dimod.INTEGER` correctly deepcopy-able
  dimod/vartypes.py
  releasenotes/notes/fix-INTEGER-deepcopy-a0dbef52bfe3a0a7.yaml
  tests/test_constrained.py
  tests/test_vartypes.py
Labels: bug/fix

#933 Fix `AdjVectorBQM.to_file` and `AdjVectorBQM.from_file`
  dimod/bqm/adjvectorbqm.pyx
  releasenotes/notes/fix-adjvector-to-file-8e56711f5d4a4233.yaml
  tests/test_adjvectorbqm.py
Labels: bug/fix

#935 Improve CQM documentation
  dimod/constrained.py
  docs/reference/constrained.rst
  docs/reference/index.rst
  releasenotes/notes/fix-cqm-labels-5a5bc59a1a969104.yaml
Labels: bug/fix, feature-request/enhancement
