Repository dwavesystems/dimod, pull requests merged in 2021-06, with the labels that each got.

#831 Fix BQM.add_bqm to correctly sum duplicates
  dimod/include/dimod/quadratic_model.h
  testscpp/tests/test_quadratic_model.cpp
Labels: bug/fix

#832 check bqm feature first pass
  dimod/core/structured.py
  tests/test_structured.py
Labels: feature-request/enhancement

#828 Reimplement BQM with new C++ code
  .gitignore
  MANIFEST.in
  dimod/binary/__init__.pxd
  dimod/binary/__init__.py
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/__init__.pxd
  dimod/binary/cybqm/__init__.py
  dimod/binary/cybqm/base.pxd
  dimod/binary/cybqm/base.pyx
  dimod/binary/cybqm/cybqm_float32.pxd
  dimod/binary/cybqm/cybqm_float32.pyx
  dimod/binary/cybqm/cybqm_float64.pxd
  dimod/binary/cybqm/cybqm_float64.pyx
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary/vartypeview.py
  dimod/bqm/utils.pyx
  dimod/compatibility23.py
  dimod/cyutilities.pxd
  dimod/cyutilities.pyx
  dimod/decorators.py
  dimod/discrete/discrete_quadratic_model.py
  dimod/include/dimod/adjvectorbqm.h
  dimod/serialization/fileview.py
  dimod/testing/asserts.py
  dimod/typing.py
  dimod/vartypes.py
  docs/reference/bqm.rst
  docs/reference/bqm_classes/adjdictbqm.rst
  docs/reference/bqm_classes/adjvectorbqm.rst
  docs/reference/bqm_classes/binary_quadratic_model.rst
  setup.cfg
  setup.py
  tests/test_adjdictbqm.py
  tests/test_bqm.py
  tests/test_cyutilities.py
  tests/test_serialization_fileview.py
Labels: backwards compatibility break

#834 Add symbolic manipulation of BQM objects
  dimod/binary/binary_quadratic_model.py
  dimod/sym.py
  tests/test_bqm.py
Labels: feature-request/enhancement

#838 Add offset to dqm
  dimod/discrete/cydiscrete_quadratic_model.pxd
  dimod/discrete/cydiscrete_quadratic_model.pyx
  dimod/discrete/discrete_quadratic_model.py
  tests/test_discrete_quadratic_model.py
Labels: feature-request/enhancement

#842 Add make_header, read_header and write_header functions
  dimod/binary/binary_quadratic_model.py
  dimod/constrained.py
  dimod/discrete/discrete_quadratic_model.py
  dimod/serialization/fileview.py
Labels: bug/fix, feature-request/enhancement

#845 Fix segmentation fault in BQM.set_linear
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  tests/test_bqm.py
Labels: bug/fix

#847 Top level bqm import
  dimod/__init__.py
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary_quadratic_model.py
  dimod/bqm/adjvectorbqm.pyx
  dimod/converters.py
  dimod/generators/constraints.py
  dimod/higherorder/utils.py
  dimod/reference/composites/connectedcomponent.py
  dimod/reference/composites/spin_transform.py
  dimod/serialization/coo.py
  dimod/serialization/json.py
  dimod/testing/asserts.py
  dimod/testing/sampler.py
  dimod/utilities.py
  tests/requirements.txt
  tests/test_binary_quadratic_model.py
  tests/test_bqm.py
  tests/test_serialization_json.py
  tests/test_variables.py
Labels: backwards compatibility break

#850 Fix NumPy deprecation warnings
  dimod/binary/binary_quadratic_model.py
  dimod/bqm/adjdictbqm.py
  dimod/core/bqm.py
  dimod/generators/random.py
  dimod/higherorder/polynomial.py
  releasenotes/notes/numpy-dtype-deprecation-db4cc55f0f0e8573.yaml
  tests/test_cyutilities.py
  tests/test_discrete_quadratic_model.py
  tests/test_sampleset.py
  tests/test_utilities.py
Labels: bug/fix

#854 Increase lower bound on setuptools
  pyproject.toml
  requirements.txt
Labels: bug/fix

#852 Fix subtracting a BQM from a number
  dimod/binary/binary_quadratic_model.py
  releasenotes/notes/fix-number-minus-bqm-aecbd763bff6dc7c.yaml
  tests/test_bqm.py
Labels: bug/fix

#853 Add Vartype.INTEGER
  dimod/typing.py
  dimod/vartypes.py
  releasenotes/notes/integer-vartype-371d5f7eb9b6c0a3.yaml
  tests/test_serialization_format.py
Labels: feature-request/enhancement

#856 README update
  README.rst
  docs/conf.py
Labels: feature-request/enhancement

#859 Add `dimod.views.quadratic.QuadraticViewsMixin`
  dimod/binary/binary_quadratic_model.py
  dimod/views/quadratic.py
  tests/test_bqm.py
Labels: feature-request/enhancement

#860 Make use of QuadraticModelBase::scale in dimod.binary.BQM
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
Labels: feature-request/enhancement

#837 add_linear_inequality_constraint to dimod
  dimod/binary/binary_quadratic_model.py
  dimod/discrete/discrete_quadratic_model.py
  releasenotes/notes/add_linear_inequality_constraint-0858233b95e3a0ab.yaml
  tests/test_bqm.py
  tests/test_discrete_quadratic_model.py
Labels: feature-request/enhancement

#844 Introduce CaseLabelDQM
  dimod/discrete/discrete_quadratic_model.py
  docs/reference/dqm.rst
  releasenotes/notes/add-caselabeldqm-6bf693b0ed189989.yaml
  tests/test_discrete_quadratic_model.py
Labels: feature-request/enhancement
