Repository dwavesystems/dimod, pull requests merged in 2022-09, with the labels that each got.

#1245 Update C++ testing framework
  .circleci/config.yml
  dimod/include/dimod/iterators.h
  dimod/include/dimod/quadratic_model.h
  testscpp/Makefile
  testscpp/test_main.cpp
  testscpp/tests/test_quadratic_model.cpp
  testscpp/tests/test_utils.cpp
Labels: bug/fix, feature-request/enhancement

#1246 Add Variables._remove() method
  dimod/cyvariables.pxd
  dimod/cyvariables.pyi
  dimod/cyvariables.pyx
  docs/reference/variables.rst
  tests/test_variables.py
Labels: feature-request/enhancement

#1243 compactified CQM equations
  dimod/constrained.py
Labels: feature-request/enhancement

#1248 Add missing release note
  releasenotes/notes/Variables._remove-fd4280eb29c6a605.yaml
Labels: bug/fix

#1249 C++ Abstract Base Class
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/constrained.py
  dimod/cylp.pyx
  dimod/cyutilities.pxd
  dimod/cyutilities.pyx
  dimod/discrete/cydiscrete_quadratic_model.pxd
  dimod/discrete/cydiscrete_quadratic_model.pyx
  dimod/include/dimod/abc.h
  dimod/include/dimod/binary_quadratic_model.h
  dimod/include/dimod/iterators.h
  dimod/include/dimod/lp.h
  dimod/include/dimod/quadratic_model.h
  dimod/include/dimod/vartypes.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  docs/reference/cpp.rst
  releasenotes/notes/c++-ABC-e6c4a5a21b3b7335.yaml
  testscpp/tests/test_binary_quadratic_model.cpp
  testscpp/tests/test_lp.cpp
  testscpp/tests/test_quadratic_model.cpp
Labels: feature-request/enhancement, backwards compatibility break

#1251 Make dimod.libcpp a Cython subpackage rather than submodule
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/cylp.pyx
  dimod/cyutilities.pxd
  dimod/cyutilities.pyx
  dimod/discrete/cydiscrete_quadratic_model.pxd
  dimod/libcpp.pxd
  dimod/libcpp/__init__.pxd
  dimod/libcpp/binary_quadratic_model.pxd
  dimod/libcpp/lp.pxd
  dimod/libcpp/quadratic_model.pxd
  dimod/libcpp/vartypes.pxd
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  releasenotes/notes/libcpp-subpackage-8c5ebf4edab00ae5.yaml
Labels: feature-request/enhancement

#1255 Restore the performance of CQM.from_file()
  dimod/constrained.py
  releasenotes/notes/fix-CQM.from_file-performance-f434f2c0e66932d4.yaml
Labels: bug/fix

#1256 Fix the weight type in CQMs with soft constraints loaded from files
  dimod/constrained.py
  releasenotes/notes/fix-CQM.from_file-weight-type-968e7f0bbf2e07ce.yaml
  tests/test_constrained.py
Labels: bug/fix
