Repository dwavesystems/dimod, pull requests merged in 2022-02, with the labels that each got.

#1093 Change BQM.resize() to return the size difference
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  releasenotes/notes/feature-BQM.resize-return-value-c0b8680d68d42ea6.yaml
  tests/test_bqm.py
Labels: feature-request/enhancement

#1094 Expose variable type bounds at the Python level
  dimod/__init__.py
  dimod/cyutilities.pxd
  dimod/cyutilities.pyx
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  docs/reference/cpp.rst
  docs/reference/vartypes.rst
  releasenotes/notes/c++vartype-info-ae0bf7b4ca0a82bd.yaml
  tests/test_cyutilities.py
Labels: feature-request/enhancement

#1097 Refactor as_samples() and add SamplesLike to typing
  dimod/sampleset.py
  dimod/typing.py
  releasenotes/notes/as-samples-refactor-589c726932e2a830.yaml
  tests/test_sampleset.py
Labels: feature-request/enhancement

#1098 Allow BQM.energies and QM.energies to handle samples with non-integer values
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/cyutilities.pxd
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  releasenotes/notes/fix-qm-real-energies-2cf8fa4e1f4a80c1.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
Labels: bug/fix

#1106 Add CQM.set_upper_bound CQM.set_lower_bound methods
  dimod/constrained.py
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  docs/reference/constrained.rst
  releasenotes/notes/non-integer-bounds-69ff82590aaaa83e.yaml
  tests/test_constrained.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#1111 Fix relabelling two model variables to the same target
  dimod/utilities.py
  releasenotes/notes/variable-relabel-dup-target-324d1ba78ac71065.yaml
  tests/test_variables.py
Labels: bug/fix

#1112 Add constraint manipulation methods
  dimod/constrained.py
  dimod/utilities.py
  docs/reference/constrained.rst
  releasenotes/notes/constraint-manipulation-05eb6e2a47b919d4.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement

#1115 Replace i<=j for i<j in quadratic model definition
  dimod/constrained.py
  dimod/quadratic/quadratic_model.py
Labels: feature-request/enhancement

#1113 Add QuadraticModel.nbytes() and BinaryQuadraticModel.nbytes() methods
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary/vartypeview.py
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  docs/reference/quadratic.rst
  releasenotes/notes/nbytes-5bd096b1cde4e561.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
  testscpp/tests/test_quadratic_model.cpp
Labels: feature-request/enhancement

#1118 Add better printing for `Comparison` objects
  dimod/sym.py
  releasenotes/notes/comparison-printing-89ab51e3f4051d9c.yaml
  tests/test_symbolic.py
Labels: feature-request/enhancement

#1117 Update intro to symbolic
  docs/intro/intro_symbolic_math.rst
Labels: feature-request/enhancement

#1126 Fix dimod.typing.Bias to exclude np.complex64
  dimod/typing.py
  releasenotes/notes/fix-bias-typing-7428ec68a481b2fa.yaml
Labels: bug/fix

#1129 Refresh ref composites and samplers
  dimod/reference/composites/truncatecomposite.py
  dimod/reference/samplers/exact_solver.py
  dimod/reference/samplers/identity_sampler.py
  dimod/reference/samplers/null_sampler.py
  dimod/reference/samplers/random_sampler.py
  dimod/reference/samplers/simulated_annealing.py
  docs/reference/sampler_composites/samplers.rst
Labels: feature-request/enhancement

#1131 Fix dimod.serialization.load() to correct propagate KeyErrors
  dimod/serialization/fileview.py
  releasenotes/notes/fix-loader-errors-5d8c7e11a8da099e.yaml
  tests/test_serialization_fileview.py
Labels: bug/fix

#1128 Remove AdjVectorBQM and AdjDictBQM
  dimod/__init__.py
  dimod/binary/binary_quadratic_model.py
  dimod/bqm/README.rst
  dimod/bqm/__init__.pxd
  dimod/bqm/__init__.py
  dimod/bqm/adjdictbqm.py
  dimod/bqm/adjvectorbqm.pxd
  dimod/bqm/adjvectorbqm.pyx
  dimod/bqm/common.pxd
  dimod/bqm/common.pyx
  dimod/bqm/construction.py
  dimod/bqm/cppbqm.pxd
  dimod/bqm/utils.pxd
  dimod/bqm/utils.pyx
  dimod/constrained.py
  dimod/core/bqm.py
  dimod/core/structured.py
  dimod/decorators.py
  dimod/discrete/cydiscrete_quadratic_model.pxd
  dimod/include/dimod/adjvectorbqm.h
  dimod/include/dimod/utils.h
  dimod/testing/sampler.py
  releasenotes/notes/remove-adjvectorbqm-21e66c31582a36ee.yaml
  setup.cfg
  setup.py
  tests/test_adjdictbqm.py
  tests/test_adjvectorbqm.py
  tests/test_bqm.py
  tests/test_constrained.py
  tests/test_legacy_bqm.py
  testscpp/Makefile
  testscpp/tests/test_bqm.cpp
Labels: backwards compatibility break
