Repository dwavesystems/dimod, pull requests merged in 2022-07, with the labels that each got.

#1222 Speed up `SampleSet.from_samples_cqm()`
  benchmarks/variables.py
  dimod/binary/cybqm/cybqm_template.pxd.pxi
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/constrained.py
  dimod/cyvariables.pyx
  dimod/quadratic/cyqm/cyqm_template.pxd.pxi
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/sampleset.py
  releasenotes/notes/faster-cqm-energies-a033a5bbdd9e6845.yaml
  tests/test_sampleset.py
  tests/test_variables.py
Labels: bug/fix, feature-request/enhancement

#1207 Add ConstrainedQuadraticModel.__str__() method
  dimod/constrained.py
  releasenotes/notes/cqm-__str__-method-b9f37742662c0810.yaml
  tests/test_constrained.py
Labels: feature-request/enhancement

#1223 Add typing support to the Variables class
  dimod/cyvariables.pyi
  dimod/cyvariables.pyx
  dimod/variables.py
  docs/reference/variables.rst
  releasenotes/notes/variables-typing-0418870faa1c71db.yaml
  tests/typing/variables.pyi
Labels: feature-request/enhancement

#1227 Add methods to clear QMs/BQMs
  dimod/binary/binary_quadratic_model.py
  dimod/binary/cybqm/cybqm_template.pyx.pxi
  dimod/binary/pybqm.py
  dimod/binary/vartypeview.py
  dimod/cyvariables.pxd
  dimod/cyvariables.pyi
  dimod/cyvariables.pyx
  dimod/include/dimod/quadratic_model.h
  dimod/libcpp.pxd
  dimod/quadratic/cyqm/cyqm_template.pyx.pxi
  dimod/quadratic/quadratic_model.py
  docs/reference/quadratic.rst
  docs/reference/variables.rst
  releasenotes/notes/clear-01fb6be66e38aaa3.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
Labels: feature-request/enhancement

#1226 Document rhs comparison requirements
  dimod/constrained.py
  docs/intro/intro_symbolic_math.rst
Labels: feature-request/enhancement

#1178 Refactor typing.Sample(s)Like
  dimod/typing.py
  releasenotes/notes/fix-typing-samplelike-ad995b7593546f88.yaml
  tests/typing/sampleslike.pyi
Labels: bug/fix

#1231 Make Vartype.INTEGER and Vartype.REAL pickleable
  dimod/vartypes.py
  releasenotes/notes/pickleable-integers-and-reals-5aee381aa12344d6.yaml
  tests/test_sampleset.py
  tests/test_vartypes.py
Labels: bug/fix

#1230 Fix as_samples() when given a sampleset and a labels_type
  dimod/sampleset.py
  releasenotes/notes/as-samples-from-sampleset-fefda032711b3044.yaml
  tests/test_bqm.py
  tests/test_quadratic_model.py
  tests/test_sampleset.py
Labels: bug/fix
